### ISSUE TITLE
Bounding box of csg geometry sometimes does not match the geometry (is much more bigger)

### ISSUE THREAD

**Issue by btjacker** [pmndrs/react-three-csg#26]
Hi, the title says everything. If you visit the sandbox and display the console, you will see inputs for the geometry and the bounding box dimensions as three sees it:

0.45 0.45 0.3      w 1.0399999618530273 h 0.6951998419106007 l 1.2901498079299927
1 1 1      w 1.0001001192212104 h 1.0001001192212104 l 1.0001001192212104

Second line is ok, component with inputs 1,1,1 has bounding box with all dimensions 1
But component with inputs 0.45 0.45 0.3 has bigger bounding box which is wrong. 
This happens only for some inputs and for example if you change "const e" value, this also affects the bounding box. 

[codesandbox](https://codesandbox.io/p/sandbox/csg-house-forked-lyy5zs?file=%2Fsrc%2FApp.js%3A28%2C9)

**Comment by JakeDluhy** [comment]
This is probably related to https://github.com/gkjohnson/three-bvh-csg/issues/183, which is fixed in version 0.0.15 of three-bvh-svg. So likely an upgrade of the library here would fix it

**Comment by btjacker** [comment]
> This is probably related to [gkjohnson/three-bvh-csg#183](https://github.com/gkjohnson/three-bvh-csg/issues/183), which is fixed in version 0.0.15 of three-bvh-svg. So likely an upgrade of the library here would fix it

I updated the codesandbox. Wireframe now shows the bounding box and with 0.0.15 it is still the same. I have tried to produce the same behaviour with pure three but the issue did not show up. Probably because of operation order.

Even in react it behave different when I do A-(B+C+D) or A-B-C-D
